// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/face_recognition/entities/face_embedding.dart';
import 'features/face_recognition/entities/person.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7529424724794210522),
    name: 'FaceEmbedding',
    lastPropertyId: const obx_int.IdUid(3, 7973591833592041287),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5323872912872406967),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1835482835479113487),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 1686990518505970108),
        hnswParams: obx_int.ModelHnswParams(dimensions: 512),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7973591833592041287),
        name: 'personId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 4591934408013799559),
        relationTarget: 'Person',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6346522834891474357),
    name: 'Person',
    lastPropertyId: const obx_int.IdUid(4, 7522260250615792543),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3624807356773581036),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7640852113564403917),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 1583944388075088930),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1539436127280537721),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7522260250615792543),
        name: 'roomId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 7269432741619826037),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6346522834891474357),
    lastIndexId: const obx_int.IdUid(4, 7269432741619826037),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FaceEmbedding: obx_int.EntityDefinition<FaceEmbedding>(
      model: _entities[0],
      toOneRelations: (FaceEmbedding object) => [object.person],
      toManyRelations: (FaceEmbedding object) => {},
      getId: (FaceEmbedding object) => object.id,
      setId: (FaceEmbedding object, int id) {
        object.id = id;
      },
      objectToFB: (FaceEmbedding object, fb.Builder fbb) {
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, embeddingOffset);
        fbb.addInt64(2, object.person.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final embeddingParam = const obx_int.Float32ListReader().vTableGet(
          buffer,
          rootOffset,
          6,
          Float32List(0),
        );
        final object = FaceEmbedding(embedding: embeddingParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.person.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.person.attach(store);
        return object;
      },
    ),
    Person: obx_int.EntityDefinition<Person>(
      model: _entities[1],
      toOneRelations: (Person object) => [],
      toManyRelations: (Person object) => {},
      getId: (Person object) => object.id,
      setId: (Person object, int id) {
        object.id = id;
      },
      objectToFB: (Person object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final roomIdOffset = fbb.writeString(object.roomId);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(3, roomIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final roomIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = Person(
          name: nameParam,
          createdAt: createdAtParam,
          roomId: roomIdParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FaceEmbedding] entity fields to define ObjectBox queries.
class FaceEmbedding_ {
  /// See [FaceEmbedding.id].
  static final id = obx.QueryIntegerProperty<FaceEmbedding>(
    _entities[0].properties[0],
  );

  /// See [FaceEmbedding.embedding].
  static final embedding = obx.QueryHnswProperty<FaceEmbedding>(
    _entities[0].properties[1],
  );

  /// See [FaceEmbedding.person].
  static final person = obx.QueryRelationToOne<FaceEmbedding, Person>(
    _entities[0].properties[2],
  );
}

/// [Person] entity fields to define ObjectBox queries.
class Person_ {
  /// See [Person.id].
  static final id = obx.QueryIntegerProperty<Person>(
    _entities[1].properties[0],
  );

  /// See [Person.name].
  static final name = obx.QueryStringProperty<Person>(
    _entities[1].properties[1],
  );

  /// See [Person.createdAt].
  static final createdAt = obx.QueryDateProperty<Person>(
    _entities[1].properties[2],
  );

  /// See [Person.roomId].
  static final roomId = obx.QueryStringProperty<Person>(
    _entities[1].properties[3],
  );
}
